# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWIndow(object):
    def setupUi(self, MainWIndow):
        MainWIndow.setObjectName("MainWIndow")
        MainWIndow.resize(524, 233)
        MainWIndow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWIndow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 111, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 171, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(240, 40, 141, 28))
        self.lineEdit.setAcceptDrops(True)
        self.lineEdit.setToolTipDuration(-1)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(240, 90, 141, 24))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 140, 121, 28))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 190, 121, 28))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color rgb(0, 0, 0)\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 140, 121, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWIndow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWIndow)
        QtCore.QMetaObject.connectSlotsByName(MainWIndow)

    def retranslateUi(self, MainWIndow):
        _translate = QtCore.QCoreApplication.translate
        MainWIndow.setWindowTitle(_translate("MainWIndow", "Conversor de Binários e Decimais"))
        self.label.setText(_translate("MainWIndow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Digite Aqui:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWIndow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Selecione a opção:</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWIndow", "Converter"))
        self.pushButton_3.setText(_translate("MainWIndow", "Sobre o programa"))
        self.pushButton_2.setText(_translate("MainWIndow", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWIndow = QtWidgets.QMainWindow()
    ui = Ui_MainWIndow()
    ui.setupUi(MainWIndow)
    MainWIndow.show()
    sys.exit(app.exec_())
